# Generated by Django 5.1.1 on 2024-10-12 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='untitled', max_length=50),
        ),
    ]
